### ISSUE TITLE
Newline adjustments on Windows?

### ISSUE THREAD

**Issue by sjakobi** [stackbuilders/atomic-write#16]
The documentation for [`System.IO.openBinaryFile`](http://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#v:openBinaryFile) says:

> On Windows, reading a file in text mode (which is the default) will translate CRLF to LF, and writing will translate LF to CRLF. This is usually what you want with text files. With binary files this is undesirable; also, as usual under Microsoft operating systems, text mode treats control-Z as EOF. Binary mode turns off all special treatment of end-of-line and end-of-file characters. (See also hSetBinaryMode.)

My current understanding is that this library opens all files in text mode and will therefore apply these newline adjustments on Windows, even for e.g. `ByteString`.

Is this correct? Could you offer binary mode variants in this case or maybe just default to binary mode for (lazy) `ByteString`s?

**Comment by cptrodolfox** [comment]
Thanks for opening this issue @sjakobi. We are taking a look, and we will get back to you.

**Comment by cptrodolfox** [comment]
Hi @sjakobi , we added new binary mode version of the functions that can be found in the .Binary of each module. (e.g. System.AtomicWrite.Writer.ByteString.Binary). These changes are now live in the latest version in hackage 0.2.0.7. Closing this issue

**Comment by sjakobi** [comment]
Many thanks for the quick response! `dhall` will be using this and I'll report back in case there are any problems!
