### ISSUE TITLE
Could not find module ‘System.PosixCompat.Files’

### ISSUE THREAD

**Issue by raxod502** [stackbuilders/atomic-write#26]
I get this when I add `atomic-write` to my project's `.cabal` file and try to `cabal v2-build`:

```
Resolving dependencies...
Build profile: -w ghc-8.8.2 -O1
In order, the following will be built (use -v for more details):
 - atomic-write-0.2.0.7 (lib) (requires build)
 - kalyn-0 (exe:kalyn) (configuration changed)
Starting     atomic-write-0.2.0.7 (lib)
Building     atomic-write-0.2.0.7 (lib)

Failed to build atomic-write-0.2.0.7.
Build log (
/home/raxod502/.cabal/logs/ghc-8.8.2/atomic-write-0.2.0.7-b62483df2180d2241be3f29b116f1d8e6315280baf54b91c552b0d9b7a5d8506.log
):
Configuring library for atomic-write-0.2.0.7..
Preprocessing library for atomic-write-0.2.0.7..
Building library for atomic-write-0.2.0.7..
[ 1 of 12] Compiling System.AtomicWrite.Internal ( src/System/AtomicWrite/Internal.hs, dist/build/System/AtomicWrite/Internal.o )

src/System/AtomicWrite/Internal.hs:21:1: error:
    Could not find module ‘System.PosixCompat.Files’
    There are files missing in the ‘unix-compat-0.5.2’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
21 | import           System.PosixCompat.Files (fileMode, getFileStatus, setFileMode)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build atomic-write-0.2.0.7 (which is required by exe:kalyn
from kalyn-0). See the build log above for details.
```

Running `ghc-pkg` returns exclusively lines noting missing files under `/usr/share/doc`, so that does not appear to be the issue.

**Comment by cptrodolfox** [comment]
Hi @raxod502, Would you mind sharing more information related to your cabal configuration?. Also, it appears that the problem is related to the dependency unix-compat not building because of the missing files. Maybe, you could try `cabal v2-clean` to clean the project's build artifacts and trigger the build again with `cabal v2-build`.

**Comment by raxod502** [comment]
I have uncovered the source of this problem. It is a bug in Cabal rather than in `atomic-write`, so I apologize for bothering you about it. Apparently, on Arch Linux I must compile with `cabal v2-build --ghc-options=-dynamic`, despite the error message saying nothing to this effect. I am disappointed by the user experience, but I don't think there is anything that `atomic-write` could possibly do about it.

Thank you!
