### ISSUE TITLE
Allow setting permissions

### ISSUE THREAD

**Issue by expipiplus1** [stackbuilders/atomic-write#8]
It would be handy to be able to set permissions for new files.

**Comment by nlander** [comment]
@expipiplus1 I have introduced https://github.com/stackbuilders/atomic-write/pull/12 , which adds a function called `atomicWriteFileWithMode`. This new function takes a `FileMode` as well as the `FilePath` and updates the permissions according to the `FileMode` after creating or modifying the file. Is this the kind of functionality you were looking for?

**Comment by expipiplus1** [comment]
Looks good! I'd consider this closed if #12 is merged.

**Comment by nlander** [comment]
PR #12 has been merged, so I am marking this issue as closed.

**Comment by expipiplus1** [comment]
Thank you!

**Comment by nlander** [comment]
@expipiplus1 You're welcome!
